### PR TITLE
Translations_04

### PR DESCRIPTION
**Pull request by solarpete**
Made the "About" page and few other terms (3 new items in the menu and 1
on the main page) translatable. This commit contains basically same
changes as the "Translations 03" commit, but with the updated
translation environment (so the handling of resource keys is different).

### CODE REVIEW

**Comment by solarpete** [comment]
Hi Chris, 

could you please check the functionality of the links in the updated About page? 

When trying out my updates on my machine only the first link in a resource key that contains more than 1 link to other URL works correctly . All others point to the first link, even though their translation is correct. E.g. here the "is available" link points to "contact us" page instead of http://openchargemap.org/site/about/funding.
image

I couldn't see the problem in the code I updated, so I suspect 2 other things can be wrong:
a) My environment (in such a way that the links are damaged).
b) The functionality that should keep the correct link in a translated term.

One way to solve the problem could be splitting the resource keys so that they contain just one link. In that case I think we should resolve the problem before posting the master file with new resource keys to Webtranslateit.

Thanks, 
Peter

**Comment by webprofusion-chrisc** [comment]
Thanks for that pete, I'll check it out.

**Comment by solarpete** [comment]
You're welcome. I was also thinking about the extensive memory requirements the resource keys for translations of long text in website pose for the mobile apps. For now I think we have following options:
1. We could separate translations for the website under one group of resource keys (I think you suggested this about a year ago when I first started working on the translations). Then the resource keys could be deleted from the language files:
a) manually,
b) using a script that would remove the whole group.
2. Keep the language files as they are (without trying to separate the website specific content from common one) and write a script that would look for the reference keys usage in web app code, keeping only the reference keys that are actually used.

If we were to use method 1., then I can try to separate the resource keys before you load them to webtranslateit. So please let me know which option you like more or if you thought of any other options. Thanks!

**Comment by webprofusion-chrisc** [comment]
Hi pete, I think the website does need to use some/all of the app resource keys but the app doesn't need many of the website one. I also think the website has a bit too much text that's not entirely necessary so we should consider first if the content that is there really needs to be. So I think (or anyone else) needs to go through the website pages and remove text which is not strictly necessary. A good example is some of the content in the About page - it's not that important who is involved for instance as that grows/changes over time. More important would be instructions on how to contribute data in bulk, how to approach data providers and ask them to license there data to us etc.

**Pull request merged**
