### PR TITLE
Translations 03, partly fixes #15

### LINKED ISSUE #15: Website: make front page and POI browsing sections translatable
Currently only the POI details page of the website has any translation applied. Extend this so that the homepage text and basic POI browsing is translatable.

### PR DESCRIPTION
**Pull request by solarpete**
Made the "About" page and few other terms (2 new items in menu and 1 on
main page) translatable.

I have not included the following files updated by grunt in this commit (not knowing whether they should be included for website translation updates as well), but if I they are necessary I will commit them as well:
API\OCM.Net\OCM.API.Web\Widgets\Map\scripts\Localisation\languagePack.min.js
App\js\Localisation\languagePack.min.js

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Thanks for taking the time to do this. However looking at the text being translated I'm not convinced that there is any value to making the About page of the website translatable. Interested parties could use google translate, for instance. The resource keys we introduce are bundled as part of the app as well as the website and this is a lot of text and nested resource complexity for us to maintain. It's also a lot of fairly unimportant text for our translators to process.

I realise this will be annoying however I don't want to make this change as it stands, translations need to concentrate on the key functionality for users browsing the OCM data, the supporting/background info (About, Developer docs etc) can be handled by in-browser translation tools and are basically too much (and of too little importance) for us to give to translators. I don't believe that these parts of the website being in English will be an obstacle for most users.

We should focus on translating the key functionality of the web app and parts of the website which serve the general public (POI browsing, POI Details etc).

Regarding the .min.js files created by grunt (and then copied throughout the solution) these are not really required in your commit as they can/will be regenerated.

**Comment by solarpete** [comment]
You're welcome. Yes, it is annoying, but I can handle that.

However I do not agree with some of your points:
- value of about page translatable: It may not have value for users that
already know the project. But for the new users it is important to know
what is the advantage of OCM over other services, i.e. it shares the data
publically and so any help to OCM will multiply its results. And the new
users can only get this from the About page.
- using google translate: Although this is usable option, it is at least
awkward to use it with the results being subpar.
- a lot of unimportant text to process: Yes, but the translators are not
forced to process it. They may if they feel like it and I suspect they will
be happy to do it. I was suprprised last time that it was a matter of only
few days before the new resource keys were translated for the major
languages. And this problem could be also handled by a short note on the
Google+, that this does not have the importance at all, if you still feel
so. I also think the translators will be happy to help if all of the OCM is
translatable. The amount of work is not so deterrent. It is rather the fact
that even though the webtranslateit says it is 100% done you just do not
see it in reality (at least that was what I was not happy about at first).
- not obstacle for users: It may not be such obstacle, but I am pretty sure
it slows down the adoption by more new users. It looks unprofessional and
gives a feeling, that the service is not mature enough to have the basic
things finished.

On the other hand I understand that having so much text in the resource
keys can be a problem for the app. However I hope this can be handled in
some creative way instead of just leaving large parts of OCM untranslated
forever.

OK, I can focus on other parts, but it would be nice to have all of OCM
translated eventually.

So I will not include the .min.js files, unless you tell me it is easier
for you to have them all in 1 commit. I generate them anyway, so it is not
a problem at all to include them right away.

**Comment by webprofusion-chrisc** [comment]
Do think there is a change we could make to the translation scheme which would allow us to translate text which has links in it? I'm looking for something which will allow us to translate large blocks instead of having to have so many resource keys. An example in the about page contributors section which has resource keys related to individuals. Ideally this would all be one resource block, with some sort of template/markup. I need to do more research here.

**Comment by solarpete** [comment]
It would be perfect, because it is a pain when you have to split sentence
into 3 parts because of the link. However I do not know of anything that
would allow us to do that. But that is mainly because this is the first web
based project I am taking part in (so far I was doing pretty much just
C/C++ and a bit of Python and Matlab scripting). In fact I do not
understand how and when is the text replaced with the translated version.
The when part would enable me to try to find out a way how to translate
text and values text and values generated by scripts, such as in
"*51930* charging
stations across *32386* locations."...

**Comment by webprofusion-chrisc** [comment]
The code which actually applies the translation is https://github.com/openchargemap/ocm-system/blob/master/App/js/OCM_CommonUI.ts#L50 on both the app and the website. We bundle all the translations into one data file then apply depending on markup in the html. This approach is OK (a little non-standard for websites, translation would normally be applied server side, for asp.net this would be normally be using a resource file).

From a quick Google we probably need to figure out how to migrate to a dedicated library such as http://i18next.com/ which has variable substitution, again I need to do more research to decide the best approach.

**Comment by solarpete** [comment]
Thanks for the link. I will try to study it a bit, but I will be very busy
next month or two, so it will take time.

Unfortunately I do not have sufficient knowledge to give any qualified
opinion on the library (future or present). However I am thinking whether
it is worth, as there are only 4 pages that contain a lot of text to
translate. Do you think it would make the work for translators much easier?
Or are you more concerned with the responsiveness of the site?

Because even though the splitting of the resource keys for the sentences
with hyperlinks is a pain, I think it should be relatively easy for the
translators to figure it out. I tried to keep them grouped (e.g. by
starting the resource keys with the same common string) so that they can
see they belong together and should be translated accordingly. But the best
way is probably to find the English originals on the page and see what it
belongs to...

**Comment by webprofusion-chrisc** [comment]
That's OK I don't expect you to do the work for this, the translations system has a problem of 'code smell' that gradually gets worse as we try and do more with this, that's my real issue and it's because I just chose a basic solution to get started with, so I need to look at it more.

**Comment by solarpete** [comment]
OK, so let me know when you decide on some solution, so that I don't work
on any translation updates before the whole system is going to be changed
(in case it is going to be changed).

**Comment by webprofusion-chrisc** [comment]
Closing earlier pull request

**Pull request closed without merging**
